[tools]
ansible = "latest"
bat = "latest"
black = "latest"
claude-code = "latest"
cmake = "latest"
conftest = "latest"
ctop = "latest"
dive = "latest"
docker-compose = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helm = "latest"
jq = "latest"
k3d = "latest"
k3sup = "latest"
k9s = "latest"
kind = "latest"
kn = "latest"
krew = "latest"
kubebuilder = "latest"
kubeconform = "latest"
kubectl = "latest"
kubectx = "latest"
kubelogin = "latest"
kubens = "latest"
kustomize = "latest"
lazydocker = "latest"
make = { version = "latest", install_env = { MAKE_CHECK_SIGNATURES = "no" } }
minikube = "latest"
neovim = "latest"
oc = "latest"
opencode = "latest"
operator-sdk = "latest"
pipx = "latest"
podman = { version = "latest", matching = "podman-remote" }
python = "latest"
redis = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
tmux = "latest"
uv = "latest"
velero = "latest"
yq = "latest"
zoxide = "latest"
