[flatpak]
remotes = [{ name = "flathub", url = "https://dl.flathub.org/repo/flathub.flatpakrepo" }]

# CLI / Server Flatpaks
cli_apps = []

gui_apps = [  # Desktop / GUI Flatpaks
  "com.brave.Browser",
  "com.spotify.Client",
  "com.visualstudio.code",
  "fr.handbrake.ghb",
  "md.obsidian.Obsidian",
  "org.gimp.GIMP",
  "org.telegram.desktop",
  "org.videolan.VLC",
  "com.getpostman.Postman",
  "com.usebruno.Bruno"
]
