[flatpak]
    remotes = [
        { name = "flathub", url = "https://dl.flathub.org/repo/flathub.flatpakrepo" }
    ]

    # CLI / Server Flatpaks
    cli_apps = []

    # Desktop / GUI Flatpaks
    gui_apps = [
        "org.wezfurlong.wezterm",
        "com.brave.Browser",
        "com.spotify.Client",
        "com.visualstudio.code",
        "dev.zed.Zed",
        "fr.handbrake.ghb",
        "md.obsidian.Obsidian",
        "org.gimp.GIMP",
        "org.telegram.desktop",
        "org.videolan.VLC"
    ]
