[packages]
common_cli = [  # Linux common CLI packages
  "flatpak",  # do not remove -> required by the flatpaks install script
  "autoconf",
  "btop",
  "curl",
  "ethtool",
  "fastfetch",
  "fortune-mod",
  "gettext",
  "git",
  "gnupg",
  "htop",
  "less",
  "lshw",
  "mosh",
  "ncdu",
  "net-tools",
  "podman",
  "stow",
  "tmux",
  "tree",
  "ufw",
  "unace",
  "unzip",
  "wakeonlan",
  "wavemon",
  "wget",
  "zip",
  "zsh"
]

common_gui = [  # Linux common GUI packages
  "alacritty",
  "gparted",
  "mpv",
  "solaar",
  "terminator"
]

[packages.debian]
cli = [  # Debian-specific CLI packages
  "7zip",
  "acpi",
  "bridge-utils",
  "build-essential",
  "exfatprogs",
  "fd-find",
  "libcurl4-openssl-dev",
  "libffi-dev",
  "libssl-dev",
  "powertop",
  "python3-pip",
  "python3-venv",
  "ripgrep",
  "xz-utils",
  "zlib1g-dev"
]
gui = [  # Debian-specific GUI packages
  "fonts-font-awesome",
  "gnome-tweaks",
  "gufw",
  "lshw-gtk"
]
kvm_cli = [  # Debian-specific KVM/hypervisor CLI packages
  "qemu-system-x86",
  "qemu-utils",
  "libvirt-daemon-system",
  "libvirt-daemon",
  "libvirt-clients",
  "virtinst",
  "cpu-checker",
  "ovmf"
]
kvm_gui = [  # Debian-specific KVM GUI packages
  "virt-manager",
  "virt-viewer",
  "qemu-system-gui"
]

[packages.ubuntu]
cli = [  # Ubuntu-specific CLI packages
  "7zip",
  "acpi",
  "bridge-utils",
  "build-essential",
  "exfatprogs",
  "libcurl4-openssl-dev",
  "libffi-dev",
  "libssl-dev",
  "powertop",
  "python3-pip",
  "python3-venv",
  "ripgrep",
  "xz-utils",
  "zlib1g-dev"
]
gui = [  # Ubuntu-specific GUI packages
  "fonts-font-awesome",
  "gnome-tweaks",
  "gufw",
  "lshw-gtk"
]
kvm_cli = [  # Ubuntu-specific KVM/hypervisor CLI packages
  "qemu-system-x86",
  "qemu-utils",
  "libvirt-daemon-system",
  "libvirt-daemon",
  "libvirt-clients",
  "virtinst",
  "cpu-checker",
  "ovmf"
]
kvm_gui = [  # Ubuntu-specific KVM GUI packages
  "virt-manager",
  "virt-viewer",
  "qemu-system-gui"
]

[packages.fedora]
cli = [  # Fedora-specific CLI packages
  "p7zip",
  "p7zip-plugins",
  "acpicli",
  "bridge-utils",
  "Development Tools",
  "exfatprogs",
  "fd-find",
  "libcurl-devel",
  "powertop",
  "python3-pip",
  "ripgrep"
]
gui = [  # Fedora-specific GUI packages
  "fontawesome-fonts",
  "gnome-tweaks",
  "lshw-gui"
]
kvm_cli = [  # Fedora-specific KVM/hypervisor CLI packages
  "qemu-system-x86",
  "qemu-utils",
  "libvirt",
  "libvirt-client",
  "virt-install",
  "edk2-ovmf"
]
kvm_gui = [  # Fedora-specific KVM GUI packages
  "virt-manager",
  "virt-viewer",
  "qemu-ui-gtk"
]

[packages.darwin]
taps = [  # Homebrew taps
  "libkrun/krun"
]
brews = [  # Hombrew brews
  "7zip",
  "btop",
  "container",
  "curl",
  "fastfetch",
  "fd",
  "fortune",
  "gemini-cli",
  "gettext",
  "git",
  "git-filter-repo",
  "gnu-sed",
  "gnupg",
  "graphviz",
  "htop",
  "mactop",
  "mise",
  "mosh",
  "ncdu",
  "pinentry-mac",
  "ripgrep",
  "stow",
  "telnet",
  "tree",
  "unar",
  "unzip",
  "wget",
  "zsh"
]
casks = [  # Homrebrew casks
  "alacritty",
  "alt-tab",
  "antigravity",
  "appcleaner",
  "brave-browser",
  "copilot-cli",
  "daisydisk",
  "font-hack-nerd-font",
  "font-meslo-lg-nerd-font",
  "ghostty",
  "gimp",
  "handbrake",
  "iterm2",
  "lm-studio",
  "microsoft-teams",
  "monitorcontrol",
  "obsidian",
  "opencode-desktop",
  "openvpn-connect",
  "orbstack",
  "podman-desktop",
  "rancher",
  "rectangle",
  "spotify",
  "stats",
  "synology-drive",
  "telegram-desktop",
  "terminator",
  "utm",
  "vagrant",
  "visual-studio-code",
  "visual-studio-code@insiders",
  "vlc",
  "wezterm",
  "whatsapp",
  "zed"
]
